version: '3.4'

services:
  webapi.dotnet:
    image: ${REGISTRY:-neuappmode}/dotnetapi:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: webapi.dotnet/Dockerfile
    ports:
      - "8080"
    environment:
      - ASPNETCORE_URLS=http://*:8080
      - ASPNETCORE_ENVIRONMENT="Docker"
